agent:
  id: "vibe"
  name: "VIBE"
  tier: 2
  role: "Senior Motion Designer"
  department: design
  reports_to: pixel

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "high"

skills:
  clawhub:
    - gifgrep
  custom: []

triggers:
  - event: "task_assigned"
    filter: { tags: ["motion", "animation", "launch", "dynamic"] }
    action: "pick_up_and_execute"
  - event: "heartbeat"
    interval: "20m"
    action: "check_motion_queue"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/motion-standards.md
  private: true
