agent:
  id: "scribe"
  name: "SCRIBE"
  tier: 2
  role: "Content Director"
  department: content
  reports_to: jarvis

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "high"

skills:
  clawhub:
    - coding-agent
  custom: []

triggers:
  - event: "task_assigned"
    filter: { tags: ["content", "writing", "copy", "editorial", "blog"] }
    action: "begin_content_work"
  - event: "heartbeat"
    interval: "10m"
    action: "check_content_queue"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/brand-voice.md
    - memory/style-guide.md
    - memory/content-calendar.md
  private: false

delegation:
  rules: []
  default: "handle_directly"
