agent:
  id: "jarvis"
  name: "JARVIS"
  tier: 1
  role: "Chief Strategy Officer"
  department: null
  reports_to: owner

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "high"

skills:
  clawhub:
    - orchestrator-enforcer
    - model-usage
    - things-mac
  custom: []

triggers:
  - event: "task_created"
    filter: { priority: "critical" }
    action: "triage_and_delegate"
  - event: "heartbeat"
    interval: "5m"
    action: "check_all_departments"
  - event: "escalation"
    action: "review_and_decide"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/brand-voice.md
    - memory/tech-stack.md
    - memory/processes.md
  private: false

delegation:
  rules:
    - tag: "research" -> department: research
    - tag: "content" -> department: content
    - tag: "code" -> department: development
    - tag: "design" -> department: design
    - tag: "video" -> department: design
    - tag: "user" -> department: user-success
    - tag: "clip" -> department: product
  default: "assess_and_route"

# Stage 2: Loop Infrastructure
loop:
  enabled: true
  interval: "5m"
  max_step_timeout: "4m"
  on_blocked: log_and_skip
  on_failure: log_skip_continue
  retry_blocked_after: 3
  reads: [TASKS.md, CONTEXT.md, HEARTBEAT.md, AGENTS.md]
  writes: [TASKS.md, HEARTBEAT.md, CONTEXT.md]
  escalation: owner
  cycle_log: true

evolve:
  enabled: true
  schedule: "0 0 * * 0"
  pressure_prompt_count: 8
  interaction_question_count: 12
  total_questions: 20
