agent:
  id: "trendy"
  name: "TRENDY"
  tier: 2
  role: "Viral Scout"
  department: research
  reports_to: atlas

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "medium"

skills:
  clawhub:
    - summarize
  custom: []

triggers:
  - event: "heartbeat"
    interval: "30m"
    action: "scan_trends"
  - event: "task_assigned"
    filter: { tags: ["trend", "viral", "social", "buzz"] }
    action: "investigate_trend"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/trend-sources.md
    - memory/signal-patterns.md
  private: false

delegation:
  rules: []
  default: "handle_directly"

# Stage 2: Loop Infrastructure
loop:
  enabled: true
  interval: "15m"
  max_step_timeout: "12m"
  on_blocked: log_and_skip
  on_failure: log_skip_continue
  retry_blocked_after: 3
  reads: [TASKS.md, CONTEXT.md, HEARTBEAT.md, AGENTS.md]
  writes: [TASKS.md, HEARTBEAT.md, CONTEXT.md]
  escalation: atlas
  cycle_log: true

evolve:
  enabled: true
  schedule: "0 0 * * 0"
  pressure_prompt_count: 5
  interaction_question_count: 15
  total_questions: 20
