agent:
  id: "nova"
  name: "NOVA"
  tier: 2
  role: "Video Production Lead"
  department: design
  reports_to: pixel

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "high"

skills:
  clawhub:
    - video-frames
    - ai-video-director
    - youtube-transcript
  custom: []

triggers:
  - event: "task_assigned"
    filter: { tags: ["video", "footage", "cinematic", "production"] }
    action: "pick_up_and_execute"
  - event: "heartbeat"
    interval: "15m"
    action: "check_video_queue"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/production-notes.md
  private: true
