agent:
  id: "pixel"
  name: "PIXEL"
  tier: 2
  role: "Lead Designer"
  department: design
  reports_to: jarvis

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "high"

skills:
  clawhub:
    - openai-image-gen
  custom: []

triggers:
  - event: "task_assigned"
    filter: { tags: ["design", "visual", "image"] }
    action: "pick_up_and_execute"
  - event: "heartbeat"
    interval: "15m"
    action: "check_design_queue"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/brand-voice.md
  private: true
