agent:
  id: "pixel"
  name: "PIXEL"
  tier: 2
  role: "Lead Designer"
  department: design
  reports_to: jarvis

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "high"

skills:
  clawhub:
    - openai-image-gen
  custom: []

triggers:
  - event: "task_assigned"
    filter: { tags: ["design", "visual", "image"] }
    action: "pick_up_and_execute"
  - event: "heartbeat"
    interval: "15m"
    action: "check_design_queue"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/brand-voice.md
  private: true

# Stage 2: Loop Infrastructure
loop:
  enabled: true
  interval: "10m"
  max_step_timeout: "8m"
  on_blocked: log_and_skip
  on_failure: log_skip_continue
  retry_blocked_after: 3
  reads: [TASKS.md, CONTEXT.md, HEARTBEAT.md, AGENTS.md]
  writes: [TASKS.md, HEARTBEAT.md, CONTEXT.md]
  escalation: jarvis
  cycle_log: true

evolve:
  enabled: true
  schedule: "0 0 * * 0"
  pressure_prompt_count: 6
  interaction_question_count: 14
  total_questions: 20
