agent:
  id: "sentinel"
  name: "SENTINEL"
  tier: 2
  role: "QA & Business Monitor"
  department: development
  reports_to: clawd

models:
  primary: "openai/gpt-5.3-codex"
  fallback: "google-gemini-cli/gemini-2.5-flash"
  thinking: "medium"

skills:
  clawhub:
    - healthcheck
    - review-pr
  custom: []

triggers:
  - event: "heartbeat"
    interval: "5m"
    action: "check_uptime"
  - event: "pr_created"
    action: "qa_review_pull_request"
  - event: "task_assigned"
    filter: { tags: ["qa", "review", "test", "validation", "monitor"] }
    action: "begin_qa_work"

channels:
  listen: [telegram, discord]
  notify: [telegram]

memory:
  seed_files:
    - memory/monitoring-targets.md
    - memory/qa-checklist.md
    - memory/incident-log.md
  private: false

delegation:
  rules: []
  default: "handle_directly"

# Stage 2: Loop Infrastructure
loop:
  enabled: true
  interval: "15m"
  max_step_timeout: "12m"
  on_blocked: log_and_skip
  on_failure: log_skip_continue
  retry_blocked_after: 3
  reads: [TASKS.md, CONTEXT.md, HEARTBEAT.md, AGENTS.md]
  writes: [TASKS.md, HEARTBEAT.md, CONTEXT.md]
  escalation: clawd
  cycle_log: true

evolve:
  enabled: true
  schedule: "0 0 * * 0"
  pressure_prompt_count: 5
  interaction_question_count: 15
  total_questions: 20
